import { animate, motion } from 'framer-motion'
import Head from 'next/head'
import Lockscreen from '../components/Lockscreen'

export default function Home() {
  return (
    <div>
      <Head>
        <title>David Nguyen - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Lockscreen />
    </div>
  )
}
